Start training PaviaU dataset
Traceback (most recent call last):
  File "/home/home_node6_1/ssy1/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/home_node6_1/ssy1/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data_ssy/latent-diffusion/experiments/models/MSTPlus.py", line 522, in <module>
    train(model, dataloader, num_epochs=args.epochs)
  File "/data_ssy/latent-diffusion/experiments/models/MSTPlus.py", line 381, in train
    loss = criterion_mrae(output, data)
  File "/home/home_node6_1/ssy1/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data_ssy/latent-diffusion/experiments/models/MSTPlus.py", line 341, in forward
    assert outputs.shape == label.shape
AssertionError
